#include once "Inc\Globals.bi"
dim shared hMainWndGlobal as HWND = NULL
dim shared hInstanceGlobal as HINSTANCE = NULL
dim shared hInstanceEXEGlobal as HINSTANCE = NULL
dim shared hPanelDlg as HWND = NULL
dim shared lpMainProcData as WNDPROCDATA ptr = NULL
dim shared lpInputOldProc as WNDPROC = NULL
dim shared bPanelVisible as WINBOOL = FALSE
dim shared hKbdHook as HHOOK = NULL
dim shared bAdvancedMode as WINBOOL = FALSE
dim shared wsGlobalSearch as WString * 1024 = ""
dim shared wsGlobalReplace as WString * 1024 = ""
dim shared wsGlobalPath as WString * 1024 = "C:\"
dim shared wsGlobalFilter as WString * 1024 = "*.txt;*.ini"
dim shared bGlobalMatchCase as WINBOOL = FALSE
dim shared bGlobalWholeWord as WINBOOL = FALSE
dim shared bGlobalAllFiles as WINBOOL = FALSE
dim shared bGlobalInFolder as WINBOOL = FALSE
dim shared wsSearchHistory(0 to MAX_HISTORY - 1) as WString * 1024
dim shared nSearchHistoryCount as integer = 0
dim shared wsReplaceHistory(0 to MAX_HISTORY - 1) as WString * 1024
dim shared nReplaceHistoryCount as integer = 0
dim shared nAdvancedPanelWidth as integer = 280
dim shared bDragging as WINBOOL = FALSE
dim shared ptDragStart as POINT
dim shared nDragStartWidth as integer = 0
dim shared hBtnClose as HWND = NULL
dim shared hLblFind as HWND = NULL
dim shared hEditSearch as HWND = NULL
dim shared hBtnClearSearch as HWND = NULL
dim shared hBtnPrev as HWND = NULL
dim shared hBtnNext as HWND = NULL
dim shared hChkMatchCase as HWND = NULL
dim shared hChkWholeWord as HWND = NULL
dim shared hChkAllFiles as HWND = NULL
dim shared hBtnAdvanced as HWND = NULL
dim shared hSideBtnClose as HWND = NULL
dim shared hSideBtnBasic as HWND = NULL
dim shared hSideLblFind as HWND = NULL
dim shared hSideEditSearch as HWND = NULL
dim shared hSideBtnClearSearch as HWND = NULL
dim shared hSideLblReplace as HWND = NULL
dim shared hSideEditReplace as HWND = NULL
dim shared hSideBtnClearReplace as HWND = NULL
dim shared hSidePath as HWND = NULL
dim shared hSideBtnBrowse as HWND = NULL
dim shared hSideChkMatchCase as HWND = NULL
dim shared hSideChkWholeWord as HWND = NULL
dim shared hSideChkAllFiles as HWND = NULL
dim shared hSideChkInFolder as HWND = NULL
dim shared hSideLblFilter as HWND = NULL
dim shared hSideEditFilter as HWND = NULL
dim shared hSideListResults as HWND = NULL
dim shared hSideBtnFindNext as HWND = NULL
dim shared hSideBtnReplace as HWND = NULL
dim shared hSideBtnReplaceAll as HWND = NULL
dim shared hSideStatus as HWND = NULL
dim shared wsIniPath as WString * 1024 = ""